CREATE TABLE user_account
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    email        VARCHAR(255)                            NOT NULL,
    nickname     VARCHAR(255)                            NOT NULL,
    provider     VARCHAR(255),
    name         VARCHAR(255),
    provider_sub VARCHAR(255),
    deleted_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_user_account PRIMARY KEY (id)
);

ALTER TABLE user_account
    ADD CONSTRAINT uc_user_account_email UNIQUE (email);